# Enables or disables the plugin entirely.
# If set to false, the plugin will not register any listeners or send messages.
enabled: true

# This contains all configurable messages handled by the plugin,
# such as join, leave, death, advancement, and system messages.
messages:

  # These messages are default for everyone and are sent for gameplay events
  # such as player join and leave.
  default:

    # Random message from this list will be sent when a player joins the server.
    join:
      - "&a%player_name% joined the server"
      - "&a%player_name% connected"

    # Random message from this list will be sent when a player leaves the server.
    leave:
      - "&c%player_name% left the server"
      - "&c%player_name% disconnected"

    # Random message from this list will be sent when a player dies.
    death:
      - "&c%player_name% met their end"
      - "&c%player_name% died"
      # - "&c%death_message%"

  # System messages used internally by the plugin.
  # These messages are shown in the console or as command feedback,
  # and are not related to gameplay events.
  system:

    # Plugin lifecycle messages.
    # These messages are sent when the plugin is enabled, disabled, or reloaded.
    lifecycle:

      # Message sent to the console when the plugin is enabled.
      enable: "Letters version %version% has been enabled."

      # Message sent to the console when the plugin is disabled.
      disable: "Letters version %version% has been disabled."

      # Message sent to the console when the plugin is reloaded.
      reload: "&aLetters version %version% has been reloaded."

      # Message sent to the console when PlaceholderAPI is detected
      placeholder-api-detected: "&aPlaceholderAPI detected! Placeholder support enabled."

      # Message sent to the console when PlaceholderAPI isn't detected
      placeholder-api-notfound: "&ePlaceholderAPI not found! Only a few placeholders like %player_name% will work. Other placeholders require installing PlaceholderAPI: https://www.spigotmc.org/resources/placeholderapi.6245/."

      # Message sent to the console when PlaceholderAPI's Player expansion pack isn't detected
      papi-player-expansion-notfound: "&ePlaceholderAPI's 'player' expansion not found! Only a few placeholders like %player_name% will work. Other placeholders require installing the 'player' expansion pack: /papi ecloud download player."

    # Command-related system messages.
    # These messages are sent to players when they interact with the plugin's commands.
    commands:

      # Message sent when no subcommand is used
      no-command: "&cYou must specify the name of the subcommand."

      # Message sent when an invalid or unknown subcommand is used.
      invalid-command: "&cCommand not found."

      # Message sent when a player does not have permission to execute a command.
      no-permission: "&cYou do not have permission to do that!"