# Enables or disables the plugin entirely.
# If set to false, the plugin will not register any listeners or send messages.
enabled: true

# This contains all configurable messages handled by the plugin,
# such as join, leave, death, advancement, and system messages.
messages:

  # These messages are default for everyone and are sent for gameplay events
  # such as player join and leave.
  default:

    # Random message from this list will be sent when a player joins the server.
    join:
      - "<green>%player_name% joined the server</green>"
      - "<green>%player_name% is now online</green>"

    # Random message from this list will be sent when a player leaves the server.
    leave:
      - "<red>%player_name% left the server</red>"
      - "<red>%player_name% went offline</red>"

    # Random message from this list will be sent when a player dies.
    death:
      - "<red>%player_name% died</red>"
      - "<red>%death_message%</red>"
      - "<red>%player_name% met their end</red>"

    # Random message from this list will be sent when a player earns an advancement
    advancement:
      - "<white>%player_name%</white> made the advancement %advancement_color%%advancement_name%!"
      - "%advancement_color%%advancement_name% <white>advancement made by %player_name%!</white>"

  # System messages used internally by the plugin.
  # These messages are shown in the console or as command feedback,
  # and are not related to gameplay events.
  system:

    # Plugin lifecycle messages.
    # These messages are sent when the plugin is enabled, disabled, or reloaded.
    lifecycle:

      # Message sent to the console when the plugin is enabled.
      enable: "Enabled Letters v%version%"

      # Message sent to the console when the plugin is disabled.
      disable: "Enabled Letters v%version%"

      # Message sent to the console when the plugin is reloaded.
      reload: "<green>Reloaded Letters v%version%</green>"

      # Message sent to the console when PlaceholderAPI is detected
      placeholder-api-detected: "<green>PlaceholderAPI detected. Placeholder support enabled.</green>"

      # Message sent to the console when PlaceholderAPI isn't detected
      placeholder-api-notfound: "<yellow>PlaceholderAPI not found. Only basic placeholders like %player_name% will work.</yellow>"

      # Message sent to the console when PlaceholderAPI's Player expansion pack isn't detected
      papi-player-expansion-notfound: "<yellow>PlaceholderAPI player expansion not found. Install it using /papi ecloud download player to enable full support.</yellow>"

    # Command-related system messages.
    # These messages are sent to players when they interact with the plugin's commands.
    commands:

      # Message sent when no subcommand is used
      no-command: "<red>You must specify a subcommand.</red>"

      # Message sent when an invalid or unknown subcommand is used.
      invalid-command: "<red>Unknown command.</red>"

      # Message sent when a player does not have permission to execute a command.
      no-permission: "<red>You do not have permission to do that.</red>"